program LicenseTester;

{
  LicenseGuard - License Tester Application
  Application to test and validate licenses generated by LicenseGuard
  
  This application demonstrates how to:
  - Load and validate license files (.sis)
  - Display license information
  - Check hardware binding
  - Verify expiration dates
  - Test feature access control
}

uses
  Vcl.Forms,
  TestMainForm in 'TestMainForm.pas' {FormLicenseTester},
  LG.Encryption in '..\..\units\LG.Encryption.pas',
  LG.LicenseData in '..\..\units\LG.LicenseData.pas',
  LG.LicenseValidator in '..\..\units\LG.LicenseValidator.pas',
  LG.HardwareInfo in '..\..\units\LG.HardwareInfo.pas',
  LG.FileVerification in '..\..\units\LG.FileVerification.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'LicenseGuard - License Tester';
  Application.CreateForm(TFormLicenseTester, FormLicenseTester);
  Application.Run;
end.
